version: "3"
services:
  mongohost:
    image: mongo:latest
    container_name: mongohost
    ports:
      - 27017:27017
  chat:
    image: "mvn-chat-ws:latest"
    container_name: chatserver
    ports:
      - 8090:8080
    links:
      - mongohost
  client:
    build:
      context: ./chat-ws-client
    container_name: chatclient
    ports:
      - 4200:80
    links:
      - chat